### ISSUE TITLE
Eel failed to show html pages after multiple refresh...

### ISSUE THREAD

**Issue by vikramsamak** [python-eel/Eel#627] opened 2022-10-22 11:50 UTC
when I purposefully refreshed the index, it failed to reload it... is there any solution for this...

Note: I'm working on data science app in which I am showing some pie charts on frontend (by fetching data from python code) and that's why I was checking the performance of eel and the I found this bug.

**Comment by zinixyt** [comment] 2022-11-01 15:03
Since i dont see any activity from the original developr im going to tell you the solution to the problem from my own experience.
Eel has a function that detects if the browser is still active, if it detects the page has been closed/refreshed it stops the python script. So, reloading is not compatible with refreshes. This feature is intended.

**Comment by 1drg** [comment] 2022-11-02 22:57
> Since i dont see any activity from the original developr im going to tell you the solution to the problem from my own experience. Eel has a function that detects if the browser is still active, if it detects the page has been closed/refreshed it stops the python script. So, reloading is not compatible with refreshes. This feature is intended.

I have been using eel for a while, and now and then I randomly get crashes when reloading a page or going to another page.

I generally get this on console: 

`WebSocket connection to 'ws://localhost:60220/eel?page=index.html' failed: `

And the eel.js file points the error to this line:

`eel._websocket = new WebSocket(websocket_addr);`

All my html files have the eel.js tag btw.

Is there anything that could be done to solve this or make it more reliable?

**Comment by vikramsamak** [comment] 2022-11-03 01:10
After seeing this many issues, I moved to another lib which also provides the facility of developing desktop based application by using HTML CSS JS.

**Comment by vikramsamak** [comment] 2022-11-03 13:30
Now I am using flaskwebgui which is based on flask.. its working great for me...

**Comment by dstricks** [comment] 2022-11-14 06:29
Hey @vikramsamak, I'm sorry you were having trouble! I hope that flaskwebgui works better for your use case. Do you by chance have a small example where the issue is easily reproducible so that I can take a look and see for myself? Or anyone else that is willing to create an example would also be appreciated.

**Comment by kobayashi-deepinsight** [comment] 2022-11-21 09:38
@dstricks 
I also face similar issues during multiple refreshes or heavy page transitions.
This tends to happen with transitions to large html pages, but it also reproduces with a very fast hit of the F5 key.

Launch [ElloWorld](https://github.com/python-eel/Eel/tree/master/examples/01%20-%20hello_world) and do a quick F5 refresh many times and you should be able to reproduce this.

**Comment by kobayashi-deepinsight** [comment] 2022-12-06 10:56
This issue was already resolved in #453.
I could have been happy if I made **shutdown_delay** large enough.

**Closed** 2024-09-02 06:50 UTC
Labels: bug
